version: "3.8"

services:
  product-service:
    build:
      context: .
      dockerfile: services/product-service/Dockerfile.local
    ports:
      - "8080:8080"
    volumes:
      - ./shared:/workspace/shared
      - ./services/product-service:/workspace/services/product-service
    environment:
      APP_PORT: 8080
    networks:
      - backend-network

  api-gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./shared:/workspace/shared
      - ./services/api-gateway:/workspace/services/api-gateway
    environment:
      PRODUCT_SERVICE_URL: http://product-service:8080
      ORDER_SERVICE_URL: http://order-service:8082
    depends_on:
      - product-service
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
